channels:
   - conda-forge

dependencies:
  - python=3.7.3
  # https://www.anaconda.com/utilizing-the-new-compilers-in-anaconda-distribution-5/
  - c-compiler=1.0.4
  - cmake=3.14.0
  - qt=5.12.5  # conda-forge does not have 5.13.2 available
  - pip
  - mpi4py
  - pip:
    - gym3
    - numpy
    - gym
    - filelock
    - kornia
    - scikit-image
    - matplotlib
    - tensorflow
    - torch
